name: Publicação do Projeto PROD

on:
  pull_request:
    branches:
      - PROD

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Realizar deploy no ambiente PROD
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_KEY }}
  qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Realizar deploy no ambiente QA
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_KEY }}

      - name: Construir URL no RENDER
        run: |
          echo "URL no RENDER: https://webservicepythonfidas.onrender.com/msg"
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Realizar deploy no ambiente PROD
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_KEY }}
      - name: Construir URL no RENDER
        run: |
          echo "URL no RENDER: https://webservicepythonfidas.onrender.com/msg"
